<option id="AD" class="country" value="AD"><?php echo gettext("AD")?></option>
<option id="AE" class="country" value="AE"><?php echo gettext("AE")?></option>
<option id="AF" class="country" value="AF"><?php echo gettext("AF")?></option>
<option id="AG" class="country" value="AG"><?php echo gettext("AG")?></option>
<option id="AI" class="country" value="AI"><?php echo gettext("AI")?></option>
<option id="AL" class="country" value="AL"><?php echo gettext("AL")?></option>
<option id="AM" class="country" value="AM"><?php echo gettext("AM")?></option>
<option id="AN" class="country" value="AN"><?php echo gettext("AN")?></option>
<option id="AO" class="country" value="AO"><?php echo gettext("AO")?></option>
<option id="AQ" class="country" value="AQ"><?php echo gettext("AQ")?></option>
<option id="AR" class="country" value="AR"><?php echo gettext("AR")?></option>
<option id="AS" class="country" value="AS"><?php echo gettext("AS")?></option>
<option id="AT" class="country" value="AT"><?php echo gettext("AT")?></option>
<option id="AU" class="country" value="AU"><?php echo gettext("AU")?></option>
<option id="AW" class="country" value="AW"><?php echo gettext("AW")?></option>
<option id="AX" class="country" value="AX"><?php echo gettext("AX")?></option>
<option id="AZ" class="country" value="AZ"><?php echo gettext("AZ")?></option>
<option id="BA" class="country" value="BA"><?php echo gettext("BA")?></option>
<option id="BB" class="country" value="BB"><?php echo gettext("BB")?></option>
<option id="BD" class="country" value="BD"><?php echo gettext("BD")?></option>
<option id="BE" class="country" value="BE"><?php echo gettext("BE")?></option>
<option id="BF" class="country" value="BF"><?php echo gettext("BF")?></option>
<option id="BG" class="country" value="BG"><?php echo gettext("BG")?></option>
<option id="BH" class="country" value="BH"><?php echo gettext("BH")?></option>
<option id="BI" class="country" value="BI"><?php echo gettext("BI")?></option>
<option id="BJ" class="country" value="BJ"><?php echo gettext("BJ")?></option>
<option id="BL" class="country" value="BL"><?php echo gettext("BL")?></option>
<option id="BM" class="country" value="BM"><?php echo gettext("BM")?></option>
<option id="BN" class="country" value="BN"><?php echo gettext("BN")?></option>
<option id="BO" class="country" value="BO"><?php echo gettext("BO")?></option>
<option id="BR" class="country" value="BR"><?php echo gettext("BR")?></option>
<option id="BS" class="country" value="BS"><?php echo gettext("BS")?></option>
<option id="BT" class="country" value="BT"><?php echo gettext("BT")?></option>
<option id="BV" class="country" value="BV"><?php echo gettext("BV")?></option>
<option id="BW" class="country" value="BW"><?php echo gettext("BW")?></option>
<option id="BY" class="country" value="BY"><?php echo gettext("BY")?></option>
<option id="BZ" class="country" value="BZ"><?php echo gettext("BZ")?></option>
<option id="CA" class="country" value="CA"><?php echo gettext("CA")?></option>
<option id="CC" class="country" value="CC"><?php echo gettext("CC")?></option>
<option id="CD" class="country" value="CD"><?php echo gettext("CD")?></option>
<option id="CF" class="country" value="CF"><?php echo gettext("CF")?></option>
<option id="CG" class="country" value="CG"><?php echo gettext("CG")?></option>
<option id="CH" class="country" value="CH"><?php echo gettext("CH")?></option>
<option id="CI" class="country" value="CI"><?php echo gettext("CI")?></option>
<option id="CK" class="country" value="CK"><?php echo gettext("CK")?></option>
<option id="CL" class="country" value="CL"><?php echo gettext("CL")?></option>
<option id="CM" class="country" value="CM"><?php echo gettext("CM")?></option>
<option id="CN" class="country" value="CN"><?php echo gettext("CN")?></option>
<option id="CO" class="country" value="CO"><?php echo gettext("CO")?></option>
<option id="CR" class="country" value="CR"><?php echo gettext("CR")?></option>
<option id="CU" class="country" value="CU"><?php echo gettext("CU")?></option>
<option id="CV" class="country" value="CV"><?php echo gettext("CV")?></option>
<option id="CX" class="country" value="CX"><?php echo gettext("CX")?></option>
<option id="CY" class="country" value="CY"><?php echo gettext("CY")?></option>
<option id="CZ" class="country" value="CZ"><?php echo gettext("CZ")?></option>
<option id="DE" class="country" value="DE"><?php echo gettext("DE")?></option>
<option id="DJ" class="country" value="DJ"><?php echo gettext("DJ")?></option>
<option id="DK" class="country" value="DK"><?php echo gettext("DK")?></option>
<option id="DM" class="country" value="DM"><?php echo gettext("DM")?></option>
<option id="DO" class="country" value="DO"><?php echo gettext("DO")?></option>
<option id="DZ" class="country" value="DZ"><?php echo gettext("DZ")?></option>
<option id="EC" class="country" value="EC"><?php echo gettext("EC")?></option>
<option id="EE" class="country" value="EE"><?php echo gettext("EE")?></option>
<option id="EG" class="country" value="EG"><?php echo gettext("EG")?></option>
<option id="EH" class="country" value="EH"><?php echo gettext("EH")?></option>
<option id="ER" class="country" value="ER"><?php echo gettext("ER")?></option>
<option id="ES" class="country" value="ES"><?php echo gettext("ES")?></option>
<option id="ET" class="country" value="ET"><?php echo gettext("ET")?></option>
<option id="FI" class="country" value="FI"><?php echo gettext("FI")?></option>
<option id="FJ" class="country" value="FJ"><?php echo gettext("FJ")?></option>
<option id="FK" class="country" value="FK"><?php echo gettext("FK")?></option>
<option id="FM" class="country" value="FM"><?php echo gettext("FM")?></option>
<option id="FO" class="country" value="FO"><?php echo gettext("FO")?></option>
<option id="FR" class="country" value="FR"><?php echo gettext("FR")?></option>
<option id="GA" class="country" value="GA"><?php echo gettext("GA")?></option>
<option id="GB" class="country" value="GB"><?php echo gettext("GB")?></option>
<option id="GD" class="country" value="GD"><?php echo gettext("GD")?></option>
<option id="GE" class="country" value="GE"><?php echo gettext("GE")?></option>
<option id="GF" class="country" value="GF"><?php echo gettext("GF")?></option>
<option id="GG" class="country" value="GG"><?php echo gettext("GG")?></option>
<option id="GH" class="country" value="GH"><?php echo gettext("GH")?></option>
<option id="GI" class="country" value="GI"><?php echo gettext("GI")?></option>
<option id="GL" class="country" value="GL"><?php echo gettext("GL")?></option>
<option id="GM" class="country" value="GM"><?php echo gettext("GM")?></option>
<option id="GN" class="country" value="GN"><?php echo gettext("GN")?></option>
<option id="GP" class="country" value="GP"><?php echo gettext("GP")?></option>
<option id="GQ" class="country" value="GQ"><?php echo gettext("GQ")?></option>
<option id="GR" class="country" value="GR"><?php echo gettext("GR")?></option>
<option id="GS" class="country" value="GS"><?php echo gettext("GS")?></option>
<option id="GT" class="country" value="GT"><?php echo gettext("GT")?></option>
<option id="GU" class="country" value="GU"><?php echo gettext("GU")?></option>
<option id="GW" class="country" value="GW"><?php echo gettext("GW")?></option>
<option id="GY" class="country" value="GY"><?php echo gettext("GY")?></option>
<option id="HK" class="country" value="HK"><?php echo gettext("HK")?></option>
<option id="HM" class="country" value="HM"><?php echo gettext("HM")?></option>
<option id="HN" class="country" value="HN"><?php echo gettext("HN")?></option>
<option id="HR" class="country" value="HR"><?php echo gettext("HR")?></option>
<option id="HT" class="country" value="HT"><?php echo gettext("HT")?></option>
<option id="HU" class="country" value="HU"><?php echo gettext("HU")?></option>
<option id="ID" class="country" value="ID"><?php echo gettext("ID")?></option>
<option id="IE" class="country" value="IE"><?php echo gettext("IE")?></option>
<option id="IL" class="country" value="IL"><?php echo gettext("IL")?></option>
<option id="IM" class="country" value="IM"><?php echo gettext("IM")?></option>
<option id="IN" class="country" value="IN"><?php echo gettext("IN")?></option>
<option id="IO" class="country" value="IO"><?php echo gettext("IO")?></option>
<option id="IQ" class="country" value="IQ"><?php echo gettext("IQ")?></option>
<option id="IR" class="country" value="IR"><?php echo gettext("IR")?></option>
<option id="IS" class="country" value="IS"><?php echo gettext("IS")?></option>
<option id="IT" class="country" value="IT"><?php echo gettext("IT")?></option>
<option id="JE" class="country" value="JE"><?php echo gettext("JE")?></option>
<option id="JM" class="country" value="JM"><?php echo gettext("JM")?></option>
<option id="JO" class="country" value="JO"><?php echo gettext("JO")?></option>
<option id="JP" class="country" value="JP"><?php echo gettext("JP")?></option>
<option id="KE" class="country" value="KE"><?php echo gettext("KE")?></option>
<option id="KG" class="country" value="KG"><?php echo gettext("KG")?></option>
<option id="KH" class="country" value="KH"><?php echo gettext("KH")?></option>
<option id="KI" class="country" value="KI"><?php echo gettext("KI")?></option>
<option id="KM" class="country" value="KM"><?php echo gettext("KM")?></option>
<option id="KN" class="country" value="KN"><?php echo gettext("KN")?></option>
<option id="KP" class="country" value="KP"><?php echo gettext("KP")?></option>
<option id="KR" class="country" value="KR"><?php echo gettext("KR")?></option>
<option id="KW" class="country" value="KW"><?php echo gettext("KW")?></option>
<option id="KY" class="country" value="KY"><?php echo gettext("KY")?></option>
<option id="KZ" class="country" value="KZ"><?php echo gettext("KZ")?></option>
<option id="LA" class="country" value="LA"><?php echo gettext("LA")?></option>
<option id="LB" class="country" value="LB"><?php echo gettext("LB")?></option>
<option id="LC" class="country" value="LC"><?php echo gettext("LC")?></option>
<option id="LI" class="country" value="LI"><?php echo gettext("LI")?></option>
<option id="LK" class="country" value="LK"><?php echo gettext("LK")?></option>
<option id="LR" class="country" value="LR"><?php echo gettext("LR")?></option>
<option id="LS" class="country" value="LS"><?php echo gettext("LS")?></option>
<option id="LT" class="country" value="LT"><?php echo gettext("LT")?></option>
<option id="LU" class="country" value="LU"><?php echo gettext("LU")?></option>
<option id="LV" class="country" value="LV"><?php echo gettext("LV")?></option>
<option id="LY" class="country" value="LY"><?php echo gettext("LY")?></option>
<option id="MA" class="country" value="MA"><?php echo gettext("MA")?></option>
<option id="MC" class="country" value="MC"><?php echo gettext("MC")?></option>
<option id="MD" class="country" value="MD"><?php echo gettext("MD")?></option>
<option id="ME" class="country" value="ME"><?php echo gettext("ME")?></option>
<option id="MF" class="country" value="MF"><?php echo gettext("MF")?></option>
<option id="MG" class="country" value="MG"><?php echo gettext("MG")?></option>
<option id="MH" class="country" value="MH"><?php echo gettext("MH")?></option>
<option id="MK" class="country" value="MK"><?php echo gettext("MK")?></option>
<option id="ML" class="country" value="ML"><?php echo gettext("ML")?></option>
<option id="MM" class="country" value="MM"><?php echo gettext("MM")?></option>
<option id="MN" class="country" value="MN"><?php echo gettext("MN")?></option>
<option id="MO" class="country" value="MO"><?php echo gettext("MO")?></option>
<option id="MP" class="country" value="MP"><?php echo gettext("MP")?></option>
<option id="MQ" class="country" value="MQ"><?php echo gettext("MQ")?></option>
<option id="MR" class="country" value="MR"><?php echo gettext("MR")?></option>
<option id="MS" class="country" value="MS"><?php echo gettext("MS")?></option>
<option id="MT" class="country" value="MT"><?php echo gettext("MT")?></option>
<option id="MU" class="country" value="MU"><?php echo gettext("MU")?></option>
<option id="MV" class="country" value="MV"><?php echo gettext("MV")?></option>
<option id="MW" class="country" value="MW"><?php echo gettext("MW")?></option>
<option id="MX" class="country" value="MX"><?php echo gettext("MX")?></option>
<option id="MY" class="country" value="MY"><?php echo gettext("MY")?></option>
<option id="MZ" class="country" value="MZ"><?php echo gettext("MZ")?></option>
<option id="NA" class="country" value="NA"><?php echo gettext("NA")?></option>
<option id="NC" class="country" value="NC"><?php echo gettext("NC")?></option>
<option id="NE" class="country" value="NE"><?php echo gettext("NE")?></option>
<option id="NF" class="country" value="NF"><?php echo gettext("NF")?></option>
<option id="NG" class="country" value="NG"><?php echo gettext("NG")?></option>
<option id="NI" class="country" value="NI"><?php echo gettext("NI")?></option>
<option id="NL" class="country" value="NL"><?php echo gettext("NL")?></option>
<option id="NO" class="country" value="NO"><?php echo gettext("NO")?></option>
<option id="NP" class="country" value="NP"><?php echo gettext("NP")?></option>
<option id="NR" class="country" value="NR"><?php echo gettext("NR")?></option>
<option id="NU" class="country" value="NU"><?php echo gettext("NU")?></option>
<option id="NZ" class="country" value="NZ"><?php echo gettext("NZ")?></option>
<option id="OM" class="country" value="OM"><?php echo gettext("OM")?></option>
<option id="PA" class="country" value="PA"><?php echo gettext("PA")?></option>
<option id="PE" class="country" value="PE"><?php echo gettext("PE")?></option>
<option id="PF" class="country" value="PF"><?php echo gettext("PF")?></option>
<option id="PG" class="country" value="PG"><?php echo gettext("PG")?></option>
<option id="PH" class="country" value="PH"><?php echo gettext("PH")?></option>
<option id="PK" class="country" value="PK"><?php echo gettext("PK")?></option>
<option id="PL" class="country" value="PL"><?php echo gettext("PL")?></option>
<option id="PM" class="country" value="PM"><?php echo gettext("PM")?></option>
<option id="PN" class="country" value="PN"><?php echo gettext("PN")?></option>
<option id="PR" class="country" value="PR"><?php echo gettext("PR")?></option>
<option id="PS" class="country" value="PS"><?php echo gettext("PS")?></option>
<option id="PT" class="country" value="PT"><?php echo gettext("PT")?></option>
<option id="PW" class="country" value="PW"><?php echo gettext("PW")?></option>
<option id="PY" class="country" value="PY"><?php echo gettext("PY")?></option>
<option id="QA" class="country" value="QA"><?php echo gettext("QA")?></option>
<option id="RE" class="country" value="RE"><?php echo gettext("RE")?></option>
<option id="RO" class="country" value="RO"><?php echo gettext("RO")?></option>
<option id="RS" class="country" value="RS"><?php echo gettext("RS")?></option>
<option id="RU" class="country" value="RU"><?php echo gettext("RU")?></option>
<option id="RW" class="country" value="RW"><?php echo gettext("RW")?></option>
<option id="SA" class="country" value="SA"><?php echo gettext("SA")?></option>
<option id="SB" class="country" value="SB"><?php echo gettext("SB")?></option>
<option id="SC" class="country" value="SC"><?php echo gettext("SC")?></option>
<option id="SD" class="country" value="SD"><?php echo gettext("SD")?></option>
<option id="SE" class="country" value="SE"><?php echo gettext("SE")?></option>
<option id="SG" class="country" value="SG"><?php echo gettext("SG")?></option>
<option id="SH" class="country" value="SH"><?php echo gettext("SH")?></option>
<option id="SI" class="country" value="SI"><?php echo gettext("SI")?></option>
<option id="SJ" class="country" value="SJ"><?php echo gettext("SJ")?></option>
<option id="SK" class="country" value="SK"><?php echo gettext("SK")?></option>
<option id="SL" class="country" value="SL"><?php echo gettext("SL")?></option>
<option id="SM" class="country" value="SM"><?php echo gettext("SM")?></option>
<option id="SN" class="country" value="SN"><?php echo gettext("SN")?></option>
<option id="SO" class="country" value="SO"><?php echo gettext("SO")?></option>
<option id="SR" class="country" value="SR"><?php echo gettext("SR")?></option>
<option id="ST" class="country" value="ST"><?php echo gettext("ST")?></option>
<option id="SV" class="country" value="SV"><?php echo gettext("SV")?></option>
<option id="SY" class="country" value="SY"><?php echo gettext("SY")?></option>
<option id="SZ" class="country" value="SZ"><?php echo gettext("SZ")?></option>
<option id="TC" class="country" value="TC"><?php echo gettext("TC")?></option>
<option id="TD" class="country" value="TD"><?php echo gettext("TD")?></option>
<option id="TF" class="country" value="TF"><?php echo gettext("TF")?></option>
<option id="TG" class="country" value="TG"><?php echo gettext("TG")?></option>
<option id="TH" class="country" value="TH"><?php echo gettext("TH")?></option>
<option id="TJ" class="country" value="TJ"><?php echo gettext("TJ")?></option>
<option id="TK" class="country" value="TK"><?php echo gettext("TK")?></option>
<option id="TL" class="country" value="TL"><?php echo gettext("TL")?></option>
<option id="TM" class="country" value="TM"><?php echo gettext("TM")?></option>
<option id="TN" class="country" value="TN"><?php echo gettext("TN")?></option>
<option id="TO" class="country" value="TO"><?php echo gettext("TO")?></option>
<option id="TR" class="country" value="TR"><?php echo gettext("TR")?></option>
<option id="TT" class="country" value="TT"><?php echo gettext("TT")?></option>
<option id="TV" class="country" value="TV"><?php echo gettext("TV")?></option>
<option id="TW" class="country" value="TW"><?php echo gettext("TW")?></option>
<option id="TZ" class="country" value="TZ"><?php echo gettext("TZ")?></option>
<option id="UA" class="country" value="UA"><?php echo gettext("UA")?></option>
<option id="UG" class="country" value="UG"><?php echo gettext("UG")?></option>
<option id="UM" class="country" value="UM"><?php echo gettext("UM")?></option>
<option id="US" class="country" value="US"><?php echo gettext("US")?></option>
<option id="UY" class="country" value="UY"><?php echo gettext("UY")?></option>
<option id="UZ" class="country" value="UZ"><?php echo gettext("UZ")?></option>
<option id="VA" class="country" value="VA"><?php echo gettext("VA")?></option>
<option id="VC" class="country" value="VC"><?php echo gettext("VC")?></option>
<option id="VE" class="country" value="VE"><?php echo gettext("VE")?></option>
<option id="VG" class="country" value="VG"><?php echo gettext("VG")?></option>
<option id="VI" class="country" value="VI"><?php echo gettext("VI")?></option>
<option id="VN" class="country" value="VN"><?php echo gettext("VN")?></option>
<option id="VU" class="country" value="VU"><?php echo gettext("VU")?></option>
<option id="WF" class="country" value="WF"><?php echo gettext("WF")?></option>
<option id="WS" class="country" value="WS"><?php echo gettext("WS")?></option>
<option id="YE" class="country" value="YE"><?php echo gettext("YE")?></option>
<option id="YT" class="country" value="YT"><?php echo gettext("YT")?></option>
<option id="ZA" class="country" value="ZA"><?php echo gettext("ZA")?></option>
<option id="ZM" class="country" value="ZM"><?php echo gettext("ZM")?></option>
<option id="ZW" class="country" value="ZW"><?php echo gettext("ZW")?></option>
