<option id="ALBERTA" class="province" value="ALBERTA"><?php echo gettext("PROVINCE_ALBERTA")?></option>
<option id="BRITISH_COLUMBIA" class="province" value="BRITISH_COLUMBIA"><?php echo gettext("PROVINCE_BRITISH_COLUMBIA")?></option>
<option id="MANITOBA" class="province" value="MANITOBA"><?php echo gettext("PROVINCE_MANITOBA")?></option>
<option id="NEWFOUNDLAND_AND_LABRADOR" class="province" value="NEWFOUNDLAND_AND_LABRADOR"><?php echo gettext("PROVINCE_NEWFOUNDLAND_AND_LABRADOR")?></option>
<option id="NEW_BRUNSWICK" class="province" value="NEW_BRUNSWICK"><?php echo gettext("PROVINCE_NEW_BRUNSWICK")?></option>
<option id="NORTHWEST_TERRITORIES" class="province" value="NORTHWEST_TERRITORIES"><?php echo gettext("PROVINCE_NORTHWEST_TERRITORIES")?></option>
<option id="NOVA_SCOTIA" class="province" value="NOVA_SCOTIA"><?php echo gettext("PROVINCE_NOVA_SCOTIA")?></option>
<option id="NUNAVUT" class="province" value="NUNAVUT"><?php echo gettext("PROVINCE_NUNAVUT")?></option>
<option id="ONTARIO" class="province" value="ONTARIO"><?php echo gettext("PROVINCE_ONTARIO")?></option>
<option id="PRINCE_EDWARD_ISLAND" class="province" value="PRINCE_EDWARD_ISLAND"><?php echo gettext("PROVINCE_PRINCE_EDWARD_ISLAND")?></option>
<option id="QUEBEC" class="province" value="QUEBEC"><?php echo gettext("PROVINCE_QUEBEC")?></option>
<option id="SASKATCHEWAN" class="province" value="SASKATCHEWAN"><?php echo gettext("PROVINCE_SASKATCHEWAN")?></option>
<option id="YUKON" class="province" value="YUKON"><?php echo gettext("PROVINCE_YUKON")?></option>
