<option id="ALABAMA" class="state" value="ALABAMA"><?php echo gettext("STATE_ALABAMA")?></option>
<option id="ALASKA" class="state" value="ALASKA"><?php echo gettext("STATE_ALASKA")?></option>
<option id="ARIZONA" class="state" value="ARIZONA"><?php echo gettext("STATE_ARIZONA")?></option>
<option id="ARKANSAS" class="state" value="ARKANSAS"><?php echo gettext("STATE_ARKANSAS")?></option>
<option id="CALIFORNIA" class="state" value="CALIFORNIA"><?php echo gettext("STATE_CALIFORNIA")?></option>
<option id="COLORADO" class="state" value="COLORADO"><?php echo gettext("STATE_COLORADO")?></option>
<option id="CONNECTICUT" class="state" value="CONNECTICUT"><?php echo gettext("STATE_CONNECTICUT")?></option>
<option id="DELAWARE" class="state" value="DELAWARE"><?php echo gettext("STATE_DELAWARE")?></option>
<option id="DISTRICT_OF_COLUMBIA" class="state" value="DISTRICT_OF_COLUMBIA"><?php echo gettext("STATE_DISTRICT_OF_COLUMBIA")?></option>
<option id="FLORIDA" class="state" value="FLORIDA"><?php echo gettext("STATE_FLORIDA")?></option>
<option id="GEORGIA_STATE" class="state" value="GEORGIA_STATE"><?php echo gettext("STATE_GEORGIA_STATE")?></option>
<option id="HAWAII" class="state" value="HAWAII"><?php echo gettext("STATE_HAWAII")?></option>
<option id="IDAHO" class="state" value="IDAHO"><?php echo gettext("STATE_IDAHO")?></option>
<option id="ILLINOIS" class="state" value="ILLINOIS"><?php echo gettext("STATE_ILLINOIS")?></option>
<option id="INDIANA" class="state" value="INDIANA"><?php echo gettext("STATE_INDIANA")?></option>
<option id="IOWA" class="state" value="IOWA"><?php echo gettext("STATE_IOWA")?></option>
<option id="KANSAS" class="state" value="KANSAS"><?php echo gettext("STATE_KANSAS")?></option>
<option id="KENTUCKY" class="state" value="KENTUCKY"><?php echo gettext("STATE_KENTUCKY")?></option>
<option id="LOUISIANA" class="state" value="LOUISIANA"><?php echo gettext("STATE_LOUISIANA")?></option>
<option id="MAINE" class="state" value="MAINE"><?php echo gettext("STATE_MAINE")?></option>
<option id="MARYLAND" class="state" value="MARYLAND"><?php echo gettext("STATE_MARYLAND")?></option>
<option id="MASSACHUSETTS" class="state" value="MASSACHUSETTS"><?php echo gettext("STATE_MASSACHUSETTS")?></option>
<option id="MICHIGAN" class="state" value="MICHIGAN"><?php echo gettext("STATE_MICHIGAN")?></option>
<option id="MINNESOTA" class="state" value="MINNESOTA"><?php echo gettext("STATE_MINNESOTA")?></option>
<option id="MISSISSIPPI" class="state" value="MISSISSIPPI"><?php echo gettext("STATE_MISSISSIPPI")?></option>
<option id="MISSOURI" class="state" value="MISSOURI"><?php echo gettext("STATE_MISSOURI")?></option>
<option id="MONTANA" class="state" value="MONTANA"><?php echo gettext("STATE_MONTANA")?></option>
<option id="NEBRASKA" class="state" value="NEBRASKA"><?php echo gettext("STATE_NEBRASKA")?></option>
<option id="NEVADA" class="state" value="NEVADA"><?php echo gettext("STATE_NEVADA")?></option>
<option id="NEW_HAMPSHIRE" class="state" value="NEW_HAMPSHIRE"><?php echo gettext("STATE_NEW_HAMPSHIRE")?></option>
<option id="NEW_JERSEY" class="state" value="NEW_JERSEY"><?php echo gettext("STATE_NEW_JERSEY")?></option>
<option id="NEW_MEXICO" class="state" value="NEW_MEXICO"><?php echo gettext("STATE_NEW_MEXICO")?></option>
<option id="NEW_YORK" class="state" value="NEW_YORK"><?php echo gettext("STATE_NEW_YORK")?></option>
<option id="NORTH_CAROLINA" class="state" value="NORTH_CAROLINA"><?php echo gettext("STATE_NORTH_CAROLINA")?></option>
<option id="NORTH_DAKOTA" class="state" value="NORTH_DAKOTA"><?php echo gettext("STATE_NORTH_DAKOTA")?></option>
<option id="OHIO" class="state" value="OHIO"><?php echo gettext("STATE_OHIO")?></option>
<option id="OKLAHOMA" class="state" value="OKLAHOMA"><?php echo gettext("STATE_OKLAHOMA")?></option>
<option id="OREGON" class="state" value="OREGON"><?php echo gettext("STATE_OREGON")?></option>
<option id="PENNSYLVANIA" class="state" value="PENNSYLVANIA"><?php echo gettext("STATE_PENNSYLVANIA")?></option>
<option id="PUERTO_RICO" class="state" value="PUERTO_RICO"><?php echo gettext("STATE_PUERTO_RICO")?></option>
<option id="RHODE_ISLAND" class="state" value="RHODE_ISLAND"><?php echo gettext("STATE_RHODE_ISLAND")?></option>
<option id="SOUTH_CAROLINA" class="state" value="SOUTH_CAROLINA"><?php echo gettext("STATE_SOUTH_CAROLINA")?></option>
<option id="SOUTH_DAKOTA" class="state" value="SOUTH_DAKOTA"><?php echo gettext("STATE_SOUTH_DAKOTA")?></option>
<option id="TENNESSEE" class="state" value="TENNESSEE"><?php echo gettext("STATE_TENNESSEE")?></option>
<option id="TEXAS" class="state" value="TEXAS"><?php echo gettext("STATE_TEXAS")?></option>
<option id="UTAH" class="state" value="UTAH"><?php echo gettext("STATE_UTAH")?></option>
<option id="VERMONT" class="state" value="VERMONT"><?php echo gettext("STATE_VERMONT")?></option>
<option id="VIRGINIA" class="state" value="VIRGINIA"><?php echo gettext("STATE_VIRGINIA")?></option>
<option id="WASHINGTON" class="state" value="WASHINGTON"><?php echo gettext("STATE_WASHINGTON")?></option>
<option id="WEST_VIRGINIA" class="state" value="WEST_VIRGINIA"><?php echo gettext("STATE_WEST_VIRGINIA")?></option>
<option id="WISCONSIN" class="state" value="WISCONSIN"><?php echo gettext("STATE_WISCONSIN")?></option>
<option id="WYOMING" class="state" value="WYOMING"><?php echo gettext("STATE_WYOMING")?></option>
