<option id="ALABAMA" class="state" value="ALABAMA"><?php echo gettext("ALABAMA")?></option>
<option id="ALASKA" class="state" value="ALASKA"><?php echo gettext("ALASKA")?></option>
<option id="ARIZONA" class="state" value="ARIZONA"><?php echo gettext("ARIZONA")?></option>
<option id="ARKANSAS" class="state" value="ARKANSAS"><?php echo gettext("ARKANSAS")?></option>
<option id="CALIFORNIA" class="state" value="CALIFORNIA"><?php echo gettext("CALIFORNIA")?></option>
<option id="COLORADO" class="state" value="COLORADO"><?php echo gettext("COLORADO")?></option>
<option id="CONNECTICUT" class="state" value="CONNECTICUT"><?php echo gettext("CONNECTICUT")?></option>
<option id="DELAWARE" class="state" value="DELAWARE"><?php echo gettext("DELAWARE")?></option>
<option id="DISTRICT_OF_COLUMBIA" class="state" value="DISTRICT_OF_COLUMBIA"><?php echo gettext("DISTRICT_OF_COLUMBIA")?></option>
<option id="FLORIDA" class="state" value="FLORIDA"><?php echo gettext("FLORIDA")?></option>
<option id="GEORGIA" class="state" value="GEORGIA"><?php echo gettext("GEORGIA")?></option>
<option id="HAWAII" class="state" value="HAWAII"><?php echo gettext("HAWAII")?></option>
<option id="IDAHO" class="state" value="IDAHO"><?php echo gettext("IDAHO")?></option>
<option id="ILLINOIS" class="state" value="ILLINOIS"><?php echo gettext("ILLINOIS")?></option>
<option id="INDIANA" class="state" value="INDIANA"><?php echo gettext("INDIANA")?></option>
<option id="IOWA" class="state" value="IOWA"><?php echo gettext("IOWA")?></option>
<option id="KANSAS" class="state" value="KANSAS"><?php echo gettext("KANSAS")?></option>
<option id="KENTUCKY" class="state" value="KENTUCKY"><?php echo gettext("KENTUCKY")?></option>
<option id="LOUISIANA" class="state" value="LOUISIANA"><?php echo gettext("LOUISIANA")?></option>
<option id="MAINE" class="state" value="MAINE"><?php echo gettext("MAINE")?></option>
<option id="MARYLAND" class="state" value="MARYLAND"><?php echo gettext("MARYLAND")?></option>
<option id="MASSACHUSETTS" class="state" value="MASSACHUSETTS"><?php echo gettext("MASSACHUSETTS")?></option>
<option id="MICHIGAN" class="state" value="MICHIGAN"><?php echo gettext("MICHIGAN")?></option>
<option id="MINNESOTA" class="state" value="MINNESOTA"><?php echo gettext("MINNESOTA")?></option>
<option id="MISSISSIPPI" class="state" value="MISSISSIPPI"><?php echo gettext("MISSISSIPPI")?></option>
<option id="MISSOURI" class="state" value="MISSOURI"><?php echo gettext("MISSOURI")?></option>
<option id="MONTANA" class="state" value="MONTANA"><?php echo gettext("MONTANA")?></option>
<option id="NEBRASKA" class="state" value="NEBRASKA"><?php echo gettext("NEBRASKA")?></option>
<option id="NEVADA" class="state" value="NEVADA"><?php echo gettext("NEVADA")?></option>
<option id="NEW_HAMPSHIRE" class="state" value="NEW_HAMPSHIRE"><?php echo gettext("NEW_HAMPSHIRE")?></option>
<option id="NEW_JERSEY" class="state" value="NEW_JERSEY"><?php echo gettext("NEW_JERSEY")?></option>
<option id="NEW_MEXICO" class="state" value="NEW_MEXICO"><?php echo gettext("NEW_MEXICO")?></option>
<option id="NEW_YORK" class="state" value="NEW_YORK"><?php echo gettext("NEW_YORK")?></option>
<option id="NORTH_CAROLINA" class="state" value="NORTH_CAROLINA"><?php echo gettext("NORTH_CAROLINA")?></option>
<option id="NORTH_DAKOTA" class="state" value="NORTH_DAKOTA"><?php echo gettext("NORTH_DAKOTA")?></option>
<option id="OHIO" class="state" value="OHIO"><?php echo gettext("OHIO")?></option>
<option id="OKLAHOMA" class="state" value="OKLAHOMA"><?php echo gettext("OKLAHOMA")?></option>
<option id="OREGON" class="state" value="OREGON"><?php echo gettext("OREGON")?></option>
<option id="PENNSYLVANIA" class="state" value="PENNSYLVANIA"><?php echo gettext("PENNSYLVANIA")?></option>
<option id="PUERTO_RICO" class="state" value="PUERTO_RICO"><?php echo gettext("PUERTO_RICO")?></option>
<option id="RHODE_ISLAND" class="state" value="RHODE_ISLAND"><?php echo gettext("RHODE_ISLAND")?></option>
<option id="SOUTH_CAROLINA" class="state" value="SOUTH_CAROLINA"><?php echo gettext("SOUTH_CAROLINA")?></option>
<option id="SOUTH_DAKOTA" class="state" value="SOUTH_DAKOTA"><?php echo gettext("SOUTH_DAKOTA")?></option>
<option id="TENNESSEE" class="state" value="TENNESSEE"><?php echo gettext("TENNESSEE")?></option>
<option id="TEXAS" class="state" value="TEXAS"><?php echo gettext("TEXAS")?></option>
<option id="UTAH" class="state" value="UTAH"><?php echo gettext("UTAH")?></option>
<option id="VERMONT" class="state" value="VERMONT"><?php echo gettext("VERMONT")?></option>
<option id="VIRGINIA" class="state" value="VIRGINIA"><?php echo gettext("VIRGINIA")?></option>
<option id="WASHINGTON" class="state" value="WASHINGTON"><?php echo gettext("WASHINGTON")?></option>
<option id="WEST_VIRGINIA" class="state" value="WEST_VIRGINIA"><?php echo gettext("WEST_VIRGINIA")?></option>
<option id="WISCONSIN" class="state" value="WISCONSIN"><?php echo gettext("WISCONSIN")?></option>
<option id="WYOMING" class="state" value="WYOMING"><?php echo gettext("WYOMING")?></option>
