<option id="AD" class="country" value="AD"><?php echo gettext("COUNTRY_AD")?></option>
<option id="AE" class="country" value="AE"><?php echo gettext("COUNTRY_AE")?></option>
<option id="AF" class="country" value="AF"><?php echo gettext("COUNTRY_AF")?></option>
<option id="AG" class="country" value="AG"><?php echo gettext("COUNTRY_AG")?></option>
<option id="AI" class="country" value="AI"><?php echo gettext("COUNTRY_AI")?></option>
<option id="AL" class="country" value="AL"><?php echo gettext("COUNTRY_AL")?></option>
<option id="AM" class="country" value="AM"><?php echo gettext("COUNTRY_AM")?></option>
<option id="AN" class="country" value="AN"><?php echo gettext("COUNTRY_AN")?></option>
<option id="AO" class="country" value="AO"><?php echo gettext("COUNTRY_AO")?></option>
<option id="AQ" class="country" value="AQ"><?php echo gettext("COUNTRY_AQ")?></option>
<option id="AR" class="country" value="AR"><?php echo gettext("COUNTRY_AR")?></option>
<option id="AS" class="country" value="AS"><?php echo gettext("COUNTRY_AS")?></option>
<option id="AT" class="country" value="AT"><?php echo gettext("COUNTRY_AT")?></option>
<option id="AU" class="country" value="AU"><?php echo gettext("COUNTRY_AU")?></option>
<option id="AW" class="country" value="AW"><?php echo gettext("COUNTRY_AW")?></option>
<option id="AX" class="country" value="AX"><?php echo gettext("COUNTRY_AX")?></option>
<option id="AZ" class="country" value="AZ"><?php echo gettext("COUNTRY_AZ")?></option>
<option id="BA" class="country" value="BA"><?php echo gettext("COUNTRY_BA")?></option>
<option id="BB" class="country" value="BB"><?php echo gettext("COUNTRY_BB")?></option>
<option id="BD" class="country" value="BD"><?php echo gettext("COUNTRY_BD")?></option>
<option id="BE" class="country" value="BE"><?php echo gettext("COUNTRY_BE")?></option>
<option id="BF" class="country" value="BF"><?php echo gettext("COUNTRY_BF")?></option>
<option id="BG" class="country" value="BG"><?php echo gettext("COUNTRY_BG")?></option>
<option id="BH" class="country" value="BH"><?php echo gettext("COUNTRY_BH")?></option>
<option id="BI" class="country" value="BI"><?php echo gettext("COUNTRY_BI")?></option>
<option id="BJ" class="country" value="BJ"><?php echo gettext("COUNTRY_BJ")?></option>
<option id="BL" class="country" value="BL"><?php echo gettext("COUNTRY_BL")?></option>
<option id="BM" class="country" value="BM"><?php echo gettext("COUNTRY_BM")?></option>
<option id="BN" class="country" value="BN"><?php echo gettext("COUNTRY_BN")?></option>
<option id="BO" class="country" value="BO"><?php echo gettext("COUNTRY_BO")?></option>
<option id="BR" class="country" value="BR"><?php echo gettext("COUNTRY_BR")?></option>
<option id="BS" class="country" value="BS"><?php echo gettext("COUNTRY_BS")?></option>
<option id="BT" class="country" value="BT"><?php echo gettext("COUNTRY_BT")?></option>
<option id="BV" class="country" value="BV"><?php echo gettext("COUNTRY_BV")?></option>
<option id="BW" class="country" value="BW"><?php echo gettext("COUNTRY_BW")?></option>
<option id="BY" class="country" value="BY"><?php echo gettext("COUNTRY_BY")?></option>
<option id="BZ" class="country" value="BZ"><?php echo gettext("COUNTRY_BZ")?></option>
<option id="CA" class="country" value="CA"><?php echo gettext("COUNTRY_CA")?></option>
<option id="CC" class="country" value="CC"><?php echo gettext("COUNTRY_CC")?></option>
<option id="CD" class="country" value="CD"><?php echo gettext("COUNTRY_CD")?></option>
<option id="CF" class="country" value="CF"><?php echo gettext("COUNTRY_CF")?></option>
<option id="CG" class="country" value="CG"><?php echo gettext("COUNTRY_CG")?></option>
<option id="CH" class="country" value="CH"><?php echo gettext("COUNTRY_CH")?></option>
<option id="CI" class="country" value="CI"><?php echo gettext("COUNTRY_CI")?></option>
<option id="CK" class="country" value="CK"><?php echo gettext("COUNTRY_CK")?></option>
<option id="CL" class="country" value="CL"><?php echo gettext("COUNTRY_CL")?></option>
<option id="CM" class="country" value="CM"><?php echo gettext("COUNTRY_CM")?></option>
<option id="CN" class="country" value="CN"><?php echo gettext("COUNTRY_CN")?></option>
<option id="CO" class="country" value="CO"><?php echo gettext("COUNTRY_CO")?></option>
<option id="CR" class="country" value="CR"><?php echo gettext("COUNTRY_CR")?></option>
<option id="CU" class="country" value="CU"><?php echo gettext("COUNTRY_CU")?></option>
<option id="CV" class="country" value="CV"><?php echo gettext("COUNTRY_CV")?></option>
<option id="CX" class="country" value="CX"><?php echo gettext("COUNTRY_CX")?></option>
<option id="CY" class="country" value="CY"><?php echo gettext("COUNTRY_CY")?></option>
<option id="CZ" class="country" value="CZ"><?php echo gettext("COUNTRY_CZ")?></option>
<option id="DE" class="country" value="DE"><?php echo gettext("COUNTRY_DE")?></option>
<option id="DJ" class="country" value="DJ"><?php echo gettext("COUNTRY_DJ")?></option>
<option id="DK" class="country" value="DK"><?php echo gettext("COUNTRY_DK")?></option>
<option id="DM" class="country" value="DM"><?php echo gettext("COUNTRY_DM")?></option>
<option id="DO" class="country" value="DO"><?php echo gettext("COUNTRY_DO")?></option>
<option id="DZ" class="country" value="DZ"><?php echo gettext("COUNTRY_DZ")?></option>
<option id="EC" class="country" value="EC"><?php echo gettext("COUNTRY_EC")?></option>
<option id="EE" class="country" value="EE"><?php echo gettext("COUNTRY_EE")?></option>
<option id="EG" class="country" value="EG"><?php echo gettext("COUNTRY_EG")?></option>
<option id="EH" class="country" value="EH"><?php echo gettext("COUNTRY_EH")?></option>
<option id="ER" class="country" value="ER"><?php echo gettext("COUNTRY_ER")?></option>
<option id="ES" class="country" value="ES"><?php echo gettext("COUNTRY_ES")?></option>
<option id="ET" class="country" value="ET"><?php echo gettext("COUNTRY_ET")?></option>
<option id="FI" class="country" value="FI"><?php echo gettext("COUNTRY_FI")?></option>
<option id="FJ" class="country" value="FJ"><?php echo gettext("COUNTRY_FJ")?></option>
<option id="FK" class="country" value="FK"><?php echo gettext("COUNTRY_FK")?></option>
<option id="FM" class="country" value="FM"><?php echo gettext("COUNTRY_FM")?></option>
<option id="FO" class="country" value="FO"><?php echo gettext("COUNTRY_FO")?></option>
<option id="FR" class="country" value="FR"><?php echo gettext("COUNTRY_FR")?></option>
<option id="GA" class="country" value="GA"><?php echo gettext("COUNTRY_GA")?></option>
<option id="GB" class="country" value="GB"><?php echo gettext("COUNTRY_GB")?></option>
<option id="GD" class="country" value="GD"><?php echo gettext("COUNTRY_GD")?></option>
<option id="GE" class="country" value="GE"><?php echo gettext("COUNTRY_GE")?></option>
<option id="GF" class="country" value="GF"><?php echo gettext("COUNTRY_GF")?></option>
<option id="GG" class="country" value="GG"><?php echo gettext("COUNTRY_GG")?></option>
<option id="GH" class="country" value="GH"><?php echo gettext("COUNTRY_GH")?></option>
<option id="GI" class="country" value="GI"><?php echo gettext("COUNTRY_GI")?></option>
<option id="GL" class="country" value="GL"><?php echo gettext("COUNTRY_GL")?></option>
<option id="GM" class="country" value="GM"><?php echo gettext("COUNTRY_GM")?></option>
<option id="GN" class="country" value="GN"><?php echo gettext("COUNTRY_GN")?></option>
<option id="GP" class="country" value="GP"><?php echo gettext("COUNTRY_GP")?></option>
<option id="GQ" class="country" value="GQ"><?php echo gettext("COUNTRY_GQ")?></option>
<option id="GR" class="country" value="GR"><?php echo gettext("COUNTRY_GR")?></option>
<option id="GS" class="country" value="GS"><?php echo gettext("COUNTRY_GS")?></option>
<option id="GT" class="country" value="GT"><?php echo gettext("COUNTRY_GT")?></option>
<option id="GU" class="country" value="GU"><?php echo gettext("COUNTRY_GU")?></option>
<option id="GW" class="country" value="GW"><?php echo gettext("COUNTRY_GW")?></option>
<option id="GY" class="country" value="GY"><?php echo gettext("COUNTRY_GY")?></option>
<option id="HK" class="country" value="HK"><?php echo gettext("COUNTRY_HK")?></option>
<option id="HM" class="country" value="HM"><?php echo gettext("COUNTRY_HM")?></option>
<option id="HN" class="country" value="HN"><?php echo gettext("COUNTRY_HN")?></option>
<option id="HR" class="country" value="HR"><?php echo gettext("COUNTRY_HR")?></option>
<option id="HT" class="country" value="HT"><?php echo gettext("COUNTRY_HT")?></option>
<option id="HU" class="country" value="HU"><?php echo gettext("COUNTRY_HU")?></option>
<option id="ID" class="country" value="ID"><?php echo gettext("COUNTRY_ID")?></option>
<option id="IE" class="country" value="IE"><?php echo gettext("COUNTRY_IE")?></option>
<option id="IL" class="country" value="IL"><?php echo gettext("COUNTRY_IL")?></option>
<option id="IM" class="country" value="IM"><?php echo gettext("COUNTRY_IM")?></option>
<option id="IN" class="country" value="IN"><?php echo gettext("COUNTRY_IN")?></option>
<option id="IO" class="country" value="IO"><?php echo gettext("COUNTRY_IO")?></option>
<option id="IQ" class="country" value="IQ"><?php echo gettext("COUNTRY_IQ")?></option>
<option id="IR" class="country" value="IR"><?php echo gettext("COUNTRY_IR")?></option>
<option id="IS" class="country" value="IS"><?php echo gettext("COUNTRY_IS")?></option>
<option id="IT" class="country" value="IT"><?php echo gettext("COUNTRY_IT")?></option>
<option id="JE" class="country" value="JE"><?php echo gettext("COUNTRY_JE")?></option>
<option id="JM" class="country" value="JM"><?php echo gettext("COUNTRY_JM")?></option>
<option id="JO" class="country" value="JO"><?php echo gettext("COUNTRY_JO")?></option>
<option id="JP" class="country" value="JP"><?php echo gettext("COUNTRY_JP")?></option>
<option id="KE" class="country" value="KE"><?php echo gettext("COUNTRY_KE")?></option>
<option id="KG" class="country" value="KG"><?php echo gettext("COUNTRY_KG")?></option>
<option id="KH" class="country" value="KH"><?php echo gettext("COUNTRY_KH")?></option>
<option id="KI" class="country" value="KI"><?php echo gettext("COUNTRY_KI")?></option>
<option id="KM" class="country" value="KM"><?php echo gettext("COUNTRY_KM")?></option>
<option id="KN" class="country" value="KN"><?php echo gettext("COUNTRY_KN")?></option>
<option id="KP" class="country" value="KP"><?php echo gettext("COUNTRY_KP")?></option>
<option id="KR" class="country" value="KR"><?php echo gettext("COUNTRY_KR")?></option>
<option id="KW" class="country" value="KW"><?php echo gettext("COUNTRY_KW")?></option>
<option id="KY" class="country" value="KY"><?php echo gettext("COUNTRY_KY")?></option>
<option id="KZ" class="country" value="KZ"><?php echo gettext("COUNTRY_KZ")?></option>
<option id="LA" class="country" value="LA"><?php echo gettext("COUNTRY_LA")?></option>
<option id="LB" class="country" value="LB"><?php echo gettext("COUNTRY_LB")?></option>
<option id="LC" class="country" value="LC"><?php echo gettext("COUNTRY_LC")?></option>
<option id="LI" class="country" value="LI"><?php echo gettext("COUNTRY_LI")?></option>
<option id="LK" class="country" value="LK"><?php echo gettext("COUNTRY_LK")?></option>
<option id="LR" class="country" value="LR"><?php echo gettext("COUNTRY_LR")?></option>
<option id="LS" class="country" value="LS"><?php echo gettext("COUNTRY_LS")?></option>
<option id="LT" class="country" value="LT"><?php echo gettext("COUNTRY_LT")?></option>
<option id="LU" class="country" value="LU"><?php echo gettext("COUNTRY_LU")?></option>
<option id="LV" class="country" value="LV"><?php echo gettext("COUNTRY_LV")?></option>
<option id="LY" class="country" value="LY"><?php echo gettext("COUNTRY_LY")?></option>
<option id="MA" class="country" value="MA"><?php echo gettext("COUNTRY_MA")?></option>
<option id="MC" class="country" value="MC"><?php echo gettext("COUNTRY_MC")?></option>
<option id="MD" class="country" value="MD"><?php echo gettext("COUNTRY_MD")?></option>
<option id="ME" class="country" value="ME"><?php echo gettext("COUNTRY_ME")?></option>
<option id="MF" class="country" value="MF"><?php echo gettext("COUNTRY_MF")?></option>
<option id="MG" class="country" value="MG"><?php echo gettext("COUNTRY_MG")?></option>
<option id="MH" class="country" value="MH"><?php echo gettext("COUNTRY_MH")?></option>
<option id="MK" class="country" value="MK"><?php echo gettext("COUNTRY_MK")?></option>
<option id="ML" class="country" value="ML"><?php echo gettext("COUNTRY_ML")?></option>
<option id="MM" class="country" value="MM"><?php echo gettext("COUNTRY_MM")?></option>
<option id="MN" class="country" value="MN"><?php echo gettext("COUNTRY_MN")?></option>
<option id="MO" class="country" value="MO"><?php echo gettext("COUNTRY_MO")?></option>
<option id="MP" class="country" value="MP"><?php echo gettext("COUNTRY_MP")?></option>
<option id="MQ" class="country" value="MQ"><?php echo gettext("COUNTRY_MQ")?></option>
<option id="MR" class="country" value="MR"><?php echo gettext("COUNTRY_MR")?></option>
<option id="MS" class="country" value="MS"><?php echo gettext("COUNTRY_MS")?></option>
<option id="MT" class="country" value="MT"><?php echo gettext("COUNTRY_MT")?></option>
<option id="MU" class="country" value="MU"><?php echo gettext("COUNTRY_MU")?></option>
<option id="MV" class="country" value="MV"><?php echo gettext("COUNTRY_MV")?></option>
<option id="MW" class="country" value="MW"><?php echo gettext("COUNTRY_MW")?></option>
<option id="MX" class="country" value="MX"><?php echo gettext("COUNTRY_MX")?></option>
<option id="MY" class="country" value="MY"><?php echo gettext("COUNTRY_MY")?></option>
<option id="MZ" class="country" value="MZ"><?php echo gettext("COUNTRY_MZ")?></option>
<option id="NA" class="country" value="NA"><?php echo gettext("COUNTRY_NA")?></option>
<option id="NC" class="country" value="NC"><?php echo gettext("COUNTRY_NC")?></option>
<option id="NE" class="country" value="NE"><?php echo gettext("COUNTRY_NE")?></option>
<option id="NF" class="country" value="NF"><?php echo gettext("COUNTRY_NF")?></option>
<option id="NG" class="country" value="NG"><?php echo gettext("COUNTRY_NG")?></option>
<option id="NI" class="country" value="NI"><?php echo gettext("COUNTRY_NI")?></option>
<option id="NL" class="country" value="NL"><?php echo gettext("COUNTRY_NL")?></option>
<option id="NO" class="country" value="NO"><?php echo gettext("COUNTRY_NO")?></option>
<option id="NP" class="country" value="NP"><?php echo gettext("COUNTRY_NP")?></option>
<option id="NR" class="country" value="NR"><?php echo gettext("COUNTRY_NR")?></option>
<option id="NU" class="country" value="NU"><?php echo gettext("COUNTRY_NU")?></option>
<option id="NZ" class="country" value="NZ"><?php echo gettext("COUNTRY_NZ")?></option>
<option id="OM" class="country" value="OM"><?php echo gettext("COUNTRY_OM")?></option>
<option id="PA" class="country" value="PA"><?php echo gettext("COUNTRY_PA")?></option>
<option id="PE" class="country" value="PE"><?php echo gettext("COUNTRY_PE")?></option>
<option id="PF" class="country" value="PF"><?php echo gettext("COUNTRY_PF")?></option>
<option id="PG" class="country" value="PG"><?php echo gettext("COUNTRY_PG")?></option>
<option id="PH" class="country" value="PH"><?php echo gettext("COUNTRY_PH")?></option>
<option id="PK" class="country" value="PK"><?php echo gettext("COUNTRY_PK")?></option>
<option id="PL" class="country" value="PL"><?php echo gettext("COUNTRY_PL")?></option>
<option id="PM" class="country" value="PM"><?php echo gettext("COUNTRY_PM")?></option>
<option id="PN" class="country" value="PN"><?php echo gettext("COUNTRY_PN")?></option>
<option id="PR" class="country" value="PR"><?php echo gettext("COUNTRY_PR")?></option>
<option id="PS" class="country" value="PS"><?php echo gettext("COUNTRY_PS")?></option>
<option id="PT" class="country" value="PT"><?php echo gettext("COUNTRY_PT")?></option>
<option id="PW" class="country" value="PW"><?php echo gettext("COUNTRY_PW")?></option>
<option id="PY" class="country" value="PY"><?php echo gettext("COUNTRY_PY")?></option>
<option id="QA" class="country" value="QA"><?php echo gettext("COUNTRY_QA")?></option>
<option id="RE" class="country" value="RE"><?php echo gettext("COUNTRY_RE")?></option>
<option id="RO" class="country" value="RO"><?php echo gettext("COUNTRY_RO")?></option>
<option id="RS" class="country" value="RS"><?php echo gettext("COUNTRY_RS")?></option>
<option id="RU" class="country" value="RU"><?php echo gettext("COUNTRY_RU")?></option>
<option id="RW" class="country" value="RW"><?php echo gettext("COUNTRY_RW")?></option>
<option id="SA" class="country" value="SA"><?php echo gettext("COUNTRY_SA")?></option>
<option id="SB" class="country" value="SB"><?php echo gettext("COUNTRY_SB")?></option>
<option id="SC" class="country" value="SC"><?php echo gettext("COUNTRY_SC")?></option>
<option id="SD" class="country" value="SD"><?php echo gettext("COUNTRY_SD")?></option>
<option id="SE" class="country" value="SE"><?php echo gettext("COUNTRY_SE")?></option>
<option id="SG" class="country" value="SG"><?php echo gettext("COUNTRY_SG")?></option>
<option id="SH" class="country" value="SH"><?php echo gettext("COUNTRY_SH")?></option>
<option id="SI" class="country" value="SI"><?php echo gettext("COUNTRY_SI")?></option>
<option id="SJ" class="country" value="SJ"><?php echo gettext("COUNTRY_SJ")?></option>
<option id="SK" class="country" value="SK"><?php echo gettext("COUNTRY_SK")?></option>
<option id="SL" class="country" value="SL"><?php echo gettext("COUNTRY_SL")?></option>
<option id="SM" class="country" value="SM"><?php echo gettext("COUNTRY_SM")?></option>
<option id="SN" class="country" value="SN"><?php echo gettext("COUNTRY_SN")?></option>
<option id="SO" class="country" value="SO"><?php echo gettext("COUNTRY_SO")?></option>
<option id="SR" class="country" value="SR"><?php echo gettext("COUNTRY_SR")?></option>
<option id="ST" class="country" value="ST"><?php echo gettext("COUNTRY_ST")?></option>
<option id="SV" class="country" value="SV"><?php echo gettext("COUNTRY_SV")?></option>
<option id="SY" class="country" value="SY"><?php echo gettext("COUNTRY_SY")?></option>
<option id="SZ" class="country" value="SZ"><?php echo gettext("COUNTRY_SZ")?></option>
<option id="TC" class="country" value="TC"><?php echo gettext("COUNTRY_TC")?></option>
<option id="TD" class="country" value="TD"><?php echo gettext("COUNTRY_TD")?></option>
<option id="TF" class="country" value="TF"><?php echo gettext("COUNTRY_TF")?></option>
<option id="TG" class="country" value="TG"><?php echo gettext("COUNTRY_TG")?></option>
<option id="TH" class="country" value="TH"><?php echo gettext("COUNTRY_TH")?></option>
<option id="TJ" class="country" value="TJ"><?php echo gettext("COUNTRY_TJ")?></option>
<option id="TK" class="country" value="TK"><?php echo gettext("COUNTRY_TK")?></option>
<option id="TL" class="country" value="TL"><?php echo gettext("COUNTRY_TL")?></option>
<option id="TM" class="country" value="TM"><?php echo gettext("COUNTRY_TM")?></option>
<option id="TN" class="country" value="TN"><?php echo gettext("COUNTRY_TN")?></option>
<option id="TO" class="country" value="TO"><?php echo gettext("COUNTRY_TO")?></option>
<option id="TR" class="country" value="TR"><?php echo gettext("COUNTRY_TR")?></option>
<option id="TT" class="country" value="TT"><?php echo gettext("COUNTRY_TT")?></option>
<option id="TV" class="country" value="TV"><?php echo gettext("COUNTRY_TV")?></option>
<option id="TW" class="country" value="TW"><?php echo gettext("COUNTRY_TW")?></option>
<option id="TZ" class="country" value="TZ"><?php echo gettext("COUNTRY_TZ")?></option>
<option id="UA" class="country" value="UA"><?php echo gettext("COUNTRY_UA")?></option>
<option id="UG" class="country" value="UG"><?php echo gettext("COUNTRY_UG")?></option>
<option id="UM" class="country" value="UM"><?php echo gettext("COUNTRY_UM")?></option>
<option id="US" class="country" value="US"><?php echo gettext("COUNTRY_US")?></option>
<option id="UY" class="country" value="UY"><?php echo gettext("COUNTRY_UY")?></option>
<option id="UZ" class="country" value="UZ"><?php echo gettext("COUNTRY_UZ")?></option>
<option id="VA" class="country" value="VA"><?php echo gettext("COUNTRY_VA")?></option>
<option id="VC" class="country" value="VC"><?php echo gettext("COUNTRY_VC")?></option>
<option id="VE" class="country" value="VE"><?php echo gettext("COUNTRY_VE")?></option>
<option id="VG" class="country" value="VG"><?php echo gettext("COUNTRY_VG")?></option>
<option id="VI" class="country" value="VI"><?php echo gettext("COUNTRY_VI")?></option>
<option id="VN" class="country" value="VN"><?php echo gettext("COUNTRY_VN")?></option>
<option id="VU" class="country" value="VU"><?php echo gettext("COUNTRY_VU")?></option>
<option id="WF" class="country" value="WF"><?php echo gettext("COUNTRY_WF")?></option>
<option id="WS" class="country" value="WS"><?php echo gettext("COUNTRY_WS")?></option>
<option id="YE" class="country" value="YE"><?php echo gettext("COUNTRY_YE")?></option>
<option id="YT" class="country" value="YT"><?php echo gettext("COUNTRY_YT")?></option>
<option id="ZA" class="country" value="ZA"><?php echo gettext("COUNTRY_ZA")?></option>
<option id="ZM" class="country" value="ZM"><?php echo gettext("COUNTRY_ZM")?></option>
<option id="ZW" class="country" value="ZW"><?php echo gettext("COUNTRY_ZW")?></option>
